# Generated by Django 5.1.2 on 2024-11-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Papelería y Escritura', 'Papelería y Escritura'), ('Cuadernos y Agendas', 'Cuadernos y Agendas'), ('Material Escolar', 'Material Escolar'), ('Arte y Manualidades', 'Arte y Manualidades'), ('Tecnología y Accesorios', 'Tecnología y Accesorios'), ('Oficina y Negocios', 'Oficina y Negocios'), ('Libros y Lectura', 'Libros y Lectura'), ('Regalos y Decoración', 'Regalos y Decoración')], default='Sin categoría', max_length=50),
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
