# Generated by Django 5.1.2 on 2024-11-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_producto_fecha_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierto', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
