# Generated by Django 5.1.2 on 2024-11-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_estadodia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadodia',
            name='fecha',
            field=models.DateField(unique=True),
        ),
    ]
