# Generated by Django 5.1.2 on 2024-11-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_estadodia_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDeVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ventas_totales', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='estadodia',
            name='abierto',
        ),
        migrations.AddField(
            model_name='estadodia',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estadodia',
            name='fecha',
            field=models.DateField(),
        ),
    ]
