# Generated by Django 5.1.2 on 2024-11-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadodiaventas',
            name='fecha',
        ),
        migrations.AddField(
            model_name='estadodiaventas',
            name='inicio_dia',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
