# Generated by Django 5.1.2 on 2024-11-27 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_estadodiaventas_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipo_documento',
            field=models.CharField(choices=[('boleta', 'Boleta'), ('factura', 'Factura')], max_length=20),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=20)),
                ('giro', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='api.venta')),
            ],
        ),
    ]
